### PR TITLE
Button Styling

### PR DESCRIPTION
**Pull request by Newton-Ephraim**
i styled the button, committed it and pushed it already.

### CODE REVIEW

**Review by KoneeVibes — CHANGES_REQUESTED** [review]
The paddings and width percentages would cause problems with responsiveness

**Comment by Newton-Ephraim** [comment]
i corrected the width and padding calculation

**Review by KoneeVibes — CHANGES_REQUESTED** [review]
The text transform is supposed to be uppercase

**Review by KoneeVibes — APPROVED** [review]
Ok, good to go!

**Pull request merged**
